# Program 2 - Peer-to-Peer Introduction
# EECE 446 - Fall 2025
# Group 17: Aaron Robinson Almazan, James C. Oppy

CC = gcc
CFLAGS = -Wall
TARGET = peer
SRC = peer.c

all: $(TARGET)

$(TARGET): $(SRC)
	$(CC) $(CFLAGS) $(SRC) -o $(TARGET)

clean:
	rm -f $(TARGET)
